version: "3.8"

services:
  database:
    image: quay.io/azavea/postgis:3-postgres12.4-slim
    environment:
      - POSTGRES_USER=franklin
      - POSTGRES_PASSWORD=franklin
      - POSTGRES_DB=franklin

  franklin:
    image: quay.io/azavea/franklin:c93f2ff
    command: ["serve", "--with-transactions"]
    environment:
      - ENVIRONMENT=development
      - DB_HOST=database
      - DB_NAME=franklin
      - DB_USER=franklin
      - DB_PASSWORD=franklin
      - AWS_PROFILE
      - AWS_REGION
    ports:
      - "9090:9090"

  catalogs-aviris:
    image: nasa-hsi-catalogs-aviris
    build:
      context: ./src/catalogs/aviris
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-nasa}
    volumes:
      - ./src/catalogs/aviris:/usr/local/src
      - $HOME/.aws:/root/.aws:ro
      - conda-pkg-cache:/opt/conda/pkgs

  activator-aviris-l1:
    image: activator
    build:
      context: ./src/pipeline/activator/
    environment:
      - STAC_API_URI=${STAC_API_URI:-http://franklin:9090}
      - S3_BUCKET=aviris-data-dev-${USER}
      - AWS_PROFILE=${AWS_PROFILE:-nasa}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./src/pipeline/activator:/usr/local/src
      - ./pipeline-data:/data
      - $HOME/.aws:/root/.aws:ro
      - conda-pkg-cache:/opt/conda/pkgs

  activator-aviris-l2:
    image: activator
    build:
      context: ./src/pipeline/activator/
    environment:
      - STAC_API_URI=${STAC_API_URI:-http://franklin:9090}
      - S3_BUCKET=aviris-data-dev-${USER}
      - AWS_PROFILE=${AWS_PROFILE:-nasa}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./src/pipeline/activator:/usr/local/src
      - ./pipeline-data:/data
      - $HOME/.aws:/root/.aws:ro
      - conda-pkg-cache:/opt/conda/pkgs

  activator-prisma:
    image: activator
    build:
      context: ./src/pipeline/activator/
    environment:
      - STAC_API_URI=${STAC_API_URI:-http://franklin:9090}
      - S3_BUCKET=prisma-data-dev-${USER}
      - AWS_PROFILE=${AWS_PROFILE:-nasa}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./src/pipeline/activator:/usr/local/src
      - ./pipeline-data:/data
      - $HOME/.aws:/root/.aws:ro
      - conda-pkg-cache:/opt/conda/pkgs

  activator-sentinel-s2:
    image: activator
    build:
      context: ./src/pipeline/activator/
    environment:
      - STAC_API_URI=${STAC_API_URI:-http://franklin:9090}
      - S3_BUCKET=sentinel-s2-data-dev-${USER}
      - AWS_PROFILE=${AWS_PROFILE:-nasa}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - AWS_REQUEST_PAYER=requester 
      - GDAL_DISABLE_READDIR_ON_OPEN=YES 
    volumes:
      - ./src/pipeline/activator:/usr/local/src
      - ./pipeline-data:/data
      - $HOME/.aws:/root/.aws:ro
      - conda-pkg-cache:/opt/conda/pkgs

  cog-clip:
    image: cog-clip
    build:
      context: ./src/pipeline/cog-clip
    environment:
      - STAC_API_URI=${STAC_API_URI:-http://franklin:9090}
      - TARGET_S3_URI=${TARGET_S3_URI:-s3://nasahyperspectral-test/activator-clip-cogs/}
      - LOG_LEVEL=${LOG_LEVEL:-TRACING}
    volumes:
      - $HOME/.aws:/root/.aws:ro

  shellcheck:
    image: koalaman/shellcheck:stable
    volumes:
      - ./:/usr/local/src
    working_dir: /usr/local/src
  
  black:
    image: cytopia/black
    volumes:
      - ./:/usr/local/src
    working_dir: /usr/local/src

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/local/src
      - ./pipeline-data:/data
      - $HOME/.aws:/root/.aws:ro
      - conda-pkg-cache:/opt/conda/pkgs
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-nasa}

volumes:
  # Persist the Conda package cache as a named volume. This package cache will
  # only be accessible when invoking Conda in-container.
  conda-pkg-cache:
