version: "3.8"

services:
  database:
    image: quay.io/azavea/postgis:3-postgres12.4-slim
    environment:
      - POSTGRES_USER=franklin
      - POSTGRES_PASSWORD=franklin
      - POSTGRES_DB=franklin

  franklin:
    image: quay.io/azavea/franklin:c93f2ff
    command: ["serve", "--with-transactions"]
    environment:
      - ENVIRONMENT=development
      - DB_HOST=database
      - DB_NAME=franklin
      - DB_USER=franklin
      - DB_PASSWORD=franklin
      - AWS_PROFILE
      - AWS_REGION
    ports:
      - "9090:9090"

  catalogs-aviris:
    image: nasa-hsi-catalogs-aviris
    build:
      context: ./src/catalogs/aviris
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-nasa}
    volumes:
      - ./src/catalogs/aviris:/usr/local/src
      - $HOME/.aws:/root/.aws:ro

  activator-aviris-l2:
    image: activator-aviris-l2
    build:
      context: ./src/pipeline/activator/aviris-l2
    environment:
      - AAL2_FRANKLIN_URL=http://franklin:9090
      - AAL2_S3_BUCKET=aviris-data-dev-${USER}
      - AWS_PROFILE=${AWS_PROFILE:-nasa}
    volumes:
      - ./src/pipeline/activator/aviris-l2:/usr/local/src
      - ./pipeline-data:/data
      - /opt/conda/pkgs:/opt/conda/pkgs
      - $HOME/.aws:/root/.aws:ro

  shellcheck:
    image: koalaman/shellcheck:stable
    volumes:
      - ./:/usr/local/src
    working_dir: /usr/local/src
  
  black:
    image: cytopia/black
    volumes:
      - ./:/usr/local/src
    working_dir: /usr/local/src

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/local/src
      - ./pipeline-data:/data
      - /opt/conda/pkgs:/opt/conda/pkgs
      - $HOME/.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-nasa}
