version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    image: nasa-hyperspectral_app
    volumes:
      - .:/workspace:cached
      - $HOME/.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-nasa}
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/workspace:cached
      - $HOME/.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-nasa}
