apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-
spec:
  entrypoint: workflow-template
  parallelism: 2
  arguments:
    parameters:
    - name: activator-input
      value: |
        [
          {
            "id": "activator-1",
            "event": "s3://aviris-data-dev-azavea/commands/aviris-l2/pipeline-test-s3.json"
          }
        ]
    - name: processor-input
      value: |
        [
          {
            "id": "processor-1",
            "event": "s3://aviris-data-dev-azavea/commands/cog-clip/pipeline-test-s3.json"
          }
        ]

  templates:
  - name: workflow-template
    dag:
      tasks:
      - name: activator
        template: activator-template
        arguments:
          parameters:
          - name: activator-input
            value: "{{item.event}}"
        withParam: "{{workflow.parameters.activator-input}}"
      
      - name: processor
        dependencies: [activator]
        template: processor-template
        arguments:
          parameters:
            - name: processor-input
              value: "{{item.event}}"
        withParam: "{{workflow.parameters.processor-input}}"

  - name: activator-template
    inputs:
      parameters:
      - name: activator-input
    container:
      image: 513167130603.dkr.ecr.us-east-1.amazonaws.com/activator:latest
      imagePullPolicy: Always # IfNotPresent
      command: [python, -m, activator.aviris.main, --l2, --pipeline-uri]
      args: ["{{inputs.parameters.activator-input}}"]
      # https://argoproj.github.io/argo-workflows/resource-duration/
      resources:
        requests:
          cpu: 3000m
          memory: 8G 
        limits:
          cpu: 3200m
          memory: 10G 

  - name: processor-template
    inputs:
      parameters:
      - name: processor-input
    container:
      image: 513167130603.dkr.ecr.us-east-1.amazonaws.com/cog-clip:latest
      imagePullPolicy: Always # IfNotPresent
      command: [java, -XX:+UseG1GC, -jar, cog-clip-assembly.jar, clip-pipeline-uri, --uri]
      args: ["{{inputs.parameters.processor-input}}"]
      # https://argoproj.github.io/argo-workflows/resource-duration/
      resources:
        requests:
          cpu: 3000m
          memory: 8G 
        limits:
          cpu: 3200m
          memory: 10G
