#!/bin/bash
set -e

function usage() {
    echo -n \
"Usage: $(basename "$0")
Generate AVIRIS Catalog and then ingest into Franklin if not already available
Example: ./scripts/catalogs-aviris
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    case "${1}" in
        --help)
            usage
            ;;
        *)
            ./scripts/server

            docker-compose run \
                --rm \
                --entrypoint python \
                --workdir="/workspace/catalogs/aviris" \
                app build_catalog.py

            echo "Importing catalog to Franklin. If this script is still running after 10 mins or so,"
            echo 'check if all items are imported with `select count(*) from collection_items;`'
            echo "in a psql shell. If they are, ctrl+c the import."
            echo "There is a Franklin bug where sometimes imports do not exit."

            docker-compose run -v "$(pwd)/catalogs/aviris/data:/data:ro" --rm franklin \
                import-catalog --catalog-root /data/catalog/catalog.json

            ;;
    esac
fi
