#!/bin/bash

set -e

if [[ -n "${NASA_HSI_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build application for staging or a release.
"   
}

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        ./scripts/update
        echo AWS_DEFAULT_REGION $AWS_DEFAULT_REGION
        ./scripts/test

        # Build the COG Clip module fat assembly jar
        pushd ./src/pipeline/activator/cog-clip
        ./sbt assembly
        popd
        
        # Build tagged container images
        GIT_COMMIT="${GIT_COMMIT}" docker-compose \
            -f docker-compose.yml \
            -f docker-compose.ci.yml \
            build

    fi
fi
