#!/bin/bash

set -e

if [[ -n "${NASA_HSI_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Publish container images to Elastic Container Registry (ECR).
"
}

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        if [[ -n "${NASA_HSI_AWS_ECR_ENDPOINT}" ]]; then
            # Evaluate the return value of the get-login subcommand, which
            # is a docker login command with temporarily ECR credentials.
            eval "$(aws ecr get-login --no-include-email)"

            # Tag and publish the Aviris L2 activator
            docker tag "activator-aviris-l2:${GIT_COMMIT}" \
                "${NASA_HSI_AWS_ECR_ENDPOINT}/activator-aviris-l2:${GIT_COMMIT}"

            docker push "${NASA_HSI_AWS_ECR_ENDPOINT}/activator-aviris-l2:${GIT_COMMIT}"
        else
            echo "ERROR: No NASA_HSI_AWS_ECR_ENDPOINT variable defined."
            exit 1
        fi
    fi
fi
