#!/bin/bash
set -e

function usage() {
    echo -n \
"Usage: $(basename "$0")
Use Docker Compose to start a console in the dev container
Example: ./scripts/console
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    case "${1}" in
        --help)
            usage
            ;;
        *)
            docker-compose run --rm --entrypoint /bin/bash dev
            ;;
    esac
fi
