#!/bin/bash
set -e

if [[ -n "${NASA_HSI_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0")
Enter a database shell.
Example: ./scripts/db-console
"
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose -f "${DIR}/../docker-compose.yml" \
                       run --rm -e PGPASSWORD=franklin \
                       database psql -U franklin -h database
    fi
    exit
fi
