#!/bin/bash
set -e

function usage() {
    echo -n \
"Usage: $(basename "$0")
Run database migrations
Example: ./scripts/migrate
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    case "${1}" in
        --help)
            usage
            ;;
        *)
            docker-compose run --rm franklin migrate
            ;;
    esac
fi
