#!/bin/bash
set -e

if [[ -n "${NASA_HSI_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
"Usage: $(basename "$0")
Use Docker Compose to start the app services
Example: ./scripts/console
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    case "${1}" in
        --help)
            usage
            ;;
        *)
            docker-compose up -d franklin
            ;;
    esac
fi
