#!/bin/bash
set -e

if [[ -n "${NASA_HSI_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
"Usage: $(basename "$0")
Setup NASA development environment
Example: ./scripts/setup
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    case "${1}" in
        --help)
            usage
            ;;
        *)
            docker-compose up -d database
            ./scripts/migrate
            ./scripts/update

            ;;
    esac
fi
