#!/bin/bash

set -e

if [[ -n "${NASA_HSI_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run tests.
"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        # Lint Bash scripts
        docker-compose \
            run --rm --no-deps shellcheck \
            scripts/*

        # Lint Python
        # docker-compose \
        #     run --rm --no-deps \
        #     black --check --diff .
    fi
fi
