#!/bin/bash

set -e

if [[ -n "${NASA_HSI_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run tests.
"
}

function argo-dry-run() {
    for filename in *.yaml; do
        argo submit "$filename" --dry-run -o yaml
    done
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        # Argo Workflows dry run
        pushd ./deployment/argo-workflows/local
        argo-dry-run
        popd

        pushd ./deployment/argo-workflows/azavea-dev
        argo-dry-run
        popd

        pushd ./deployment/argo-workflows/eks
        argo-dry-run
        popd

    fi
fi
