#!/bin/bash

set -e

if [[ -n "${NASA_HSI_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run tests.
"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        # Lint Bash scripts
        docker-compose \
            run --rm --no-deps shellcheck \
            scripts/*

        docker-compose \
            run --rm activator \
            scripts/test

        # Lint Python
        # docker-compose \
        #     run --rm --no-deps \
        #     black --check --diff .

        # build and test cog-clip assembly
        # we don't need bloop, sbt uses .bsp
        pushd ./src/pipeline/cog-clip
        ./sbt test
        popd
    fi
fi
