#!/bin/bash

set -e

if [[ -n "${NASA_HSI_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run tests.
"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        # Lint Bash scripts
        docker-compose \
            run --rm --no-deps shellcheck \
            scripts/*

        # Lint Python
        # docker-compose \
        #     run --rm --no-deps \
        #     black --check --diff .

        # build and test cog-clip assembly
        # we don't need bloop, sbt uses .bsp
        pushd ./src/pipeline/activator/cog-clip
        ./sbt test
        popd

        # Argo Workflows dry run
        pushd ./deployment/argo-workflows/local
        argo submit workflow-one.yaml --dry-run -o yaml
        argo submit workflow-two.yaml --dry-run -o yaml
        popd

        pushd ./deployment/argo-workflows/azavea-dev
        argo submit workflow-one.yaml --dry-run -o yaml
        argo submit workflow-two.yaml --dry-run -o yaml
        popd

    fi
fi
