#!/bin/bash
set -e

function usage() {
    echo -n \
"Usage: $(basename "$0")
Update all app services
Example: ./scripts/update
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    case "${1}" in
        --help)
            usage
            ;;
        *)
            docker-compose build
            ;;
    esac
fi
