name: CI STAC

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Validate STAC HSI Extension
        run: |
          cd docs/stac-spec/hsi;
          npm install && npm test
