name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.11

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/project/build.properties') }}

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_DEV_CONFIG }}
          context: azavea-dev
        id: setcontext

      - name: Install Argo CLI
        run: |
          curl -sLO https://github.com/argoproj/argo-workflows/releases/download/v3.2.6/argo-linux-amd64.gz && \
          gunzip argo-linux-amd64.gz && \
          sudo chmod +x argo-linux-amd64 && \
          sudo mv ./argo-linux-amd64 /usr/local/bin/argo && \
          argo version

      - name: Argo Workflows dry run
        run: ./scripts/test-argo

      - name: Start Franklin
        run: ./scripts/server
        
      - name: Run migrations for Franklin
        run: ./scripts/migrate

      - run: ./scripts/cibuild

      - run: ./scripts/cipublish
        if: github.ref == 'refs/heads/master'

      - run: |
          docker-compose -f docker-compose.ci.yml run --rm terraform -c "
            # Unset this to avoid a ProfileNotFound exception from the AWS CLI.
            unset AWS_PROFILE

            ./scripts/infra plan && ./scripts/infra apply
          "
        if: github.ref == 'refs/heads/master'
