name: CI

on:
  push:
    branches:
      - master
      - jrb/ci
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      # Set this to an empty string to avoid a ProfileNotFound exception from
      # the AWS CLI
      AWS_PROFILE: ""
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: ./scripts/cibuild

      - run: ./scripts/cipublish
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/jrb/ci'
        env:
          NASA_HSI_AWS_ECR_ENDPOINT: ${{ secrets.NASA_HSI_AWS_ECR_ENDPOINT }}

      - run: |
          docker-compose -f docker-compose.ci.yml run --rm terraform ./scripts/infra plan
          docker-compose -f docker-compose.ci.yml run --rm terraform ./scripts/infra apply
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/jrb/ci'
